# Use the official Python base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install the required Python libraries
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Python application file
COPY api_scheduler.py .
COPY email_service.py .

# Run the Python application
CMD ["python", "api_scheduler.py"]
